"""Document storage backends.

- LocalBackend    — encrypts with the local Envelope and writes to data/storage.
- S3Backend       — AWS S3 + KMS: a per-object data key is generated by KMS,
                    the content is AES-256-GCM encrypted client-side, and the
                    encrypted blob is stored in S3 (with SSE-KMS on top).

Both expose the same save / load / delete interface so the app never cares
which one is active (STORAGE_BACKEND env var decides).
"""
import hashlib
import os
import struct
import uuid
from pathlib import Path

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from .crypto import Envelope


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


class LocalBackend:
    backend = "local"

    def __init__(self, data_dir: Path, env_key: str | None = None):
        self.dir = data_dir / "storage"
        self.dir.mkdir(parents=True, exist_ok=True)
        self.envelope = Envelope(data_dir, env_key)

    def save(self, data: bytes, filename: str) -> dict:
        key = f"{uuid.uuid4().hex}.enc"
        (self.dir / key).write_bytes(self.envelope.encrypt(data))
        return {"key": key, "size": len(data), "sha256": _sha256(data)}

    def load(self, key: str) -> bytes:
        return self.envelope.decrypt((self.dir / key).read_bytes())

    def delete(self, key: str) -> None:
        try:
            (self.dir / key).unlink()
        except OSError:
            pass


class S3Backend:
    backend = "s3"

    def __init__(self, bucket: str, region: str, kms_key_id: str):
        import boto3  # imported lazily so local runs never need boto3 configured

        self.bucket = bucket
        self.kms_key_id = kms_key_id
        self.s3 = boto3.client("s3", region_name=region)
        self.kms = boto3.client("kms", region_name=region)

    def save(self, data: bytes, filename: str) -> dict:
        dk = self.kms.generate_data_key(KeyId=self.kms_key_id, KeySpec="AES_256")
        plaintext_key, wrapped_key = dk["Plaintext"], dk["CiphertextBlob"]
        nonce = os.urandom(12)
        ciphertext = AESGCM(plaintext_key).encrypt(nonce, data, None)
        blob = struct.pack(">I", len(wrapped_key)) + wrapped_key + nonce + ciphertext

        key = f"documents/{uuid.uuid4().hex}.enc"
        self.s3.put_object(
            Bucket=self.bucket, Key=key, Body=blob,
            ServerSideEncryption="aws:kms", SSEKMSKeyId=self.kms_key_id,
        )
        return {"key": key, "size": len(data), "sha256": _sha256(data)}

    def load(self, key: str) -> bytes:
        blob = self.s3.get_object(Bucket=self.bucket, Key=key)["Body"].read()
        (wlen,) = struct.unpack(">I", blob[:4])
        wrapped_key = blob[4:4 + wlen]
        nonce = blob[4 + wlen:16 + wlen]
        ciphertext = blob[16 + wlen:]
        plaintext_key = self.kms.decrypt(CiphertextBlob=wrapped_key)["Plaintext"]
        return AESGCM(plaintext_key).decrypt(nonce, ciphertext, None)

    def delete(self, key: str) -> None:
        try:
            self.s3.delete_object(Bucket=self.bucket, Key=key)
        except Exception:
            pass


def build_storage(config, data_dir: Path):
    if config.get("STORAGE_BACKEND") == "s3":
        if not (config.get("S3_BUCKET") and config.get("KMS_KEY_ID")):
            raise RuntimeError("STORAGE_BACKEND=s3 requires S3_BUCKET and KMS_KEY_ID")
        return S3Backend(config["S3_BUCKET"], config.get("AWS_REGION", "us-east-1"), config["KMS_KEY_ID"])
    return LocalBackend(data_dir, config.get("MASTER_KEY"))
